### ISSUE TITLE
待办事项自动清理

### ISSUE THREAD

**Issue by vegepuppy** [vegepuppy/Garnet#14]
对于一些过期待办事项，实现自动清理
- 用户选择是否要定期自动清理
- 提供主动清洗功能，例如
    - 按时间清理
    - 清理所有已完成
- 被删除链接、待办需要在TODO_LINK中删除对应的条目

**Comment by 9rz9rz** [comment]
定时自动清理不大好做，使用`PendingIntent`实现的话实在是杀鸡用牛刀。目前只做了清理所有已完成事项的功能。

如果想要清理某一时间点前所有已完成的待办，就要求重构数据储存方式。如“删除2024-09-21”之前的所有待办无法通过字符串处理得到待办事项。而如果通过时间戳获得要删除的时间， 在数据库中储存UNIX毫秒数，即可实现这功能，并且似乎也符合一般规范。

可以开学后讨论下有无此必要
