### ISSUE TITLE
Info相关类重构

### ISSUE THREAD

**Issue by vegepuppy** [vegepuppy/Garnet#16]
目前的Info相关类功能性和封装性较差，需要进行重构，初步设计如下：
- InfoItem：存储单条资料，不仅限于链接
- InfoItem要实现的功能如下：
    - 存储Info类别，如本地文件、网络资源、实体资料
    - 存储关键信息：如本地文件路径、网络资源链接
    - 存储显示信息：主要是名称，网络链接的图标（详见另一issue：链接美化）
    - 存储待办关联信息（详见另一issue，数据库链接）
    - 包含相关控件：控件应当展示显示信息、实现跳转功能（打开文件、打开链接）、实现待办的添加与生成
- InfoGroup要实现的功能如下
- InfoGroup要实现的功能如下    
    - 存储InfoItem列表
    - 存储本InfoGroup的名称

#15

**Comment by 9rz9rz** [comment]
# 重构设计

## `InfoItem`(abstract class)

methods to be implemented:

- `save()`：保存到数据库中
- `getDisplayString()`获得在`InfoItemDisplayActivity()`中显示的字符串
- `display()`用一个新的Activity显示这个`InfoItem`的内容

原本的`InfoItem`类重命名为`LinkInfoItem extends InfoItem`，新建类`NoteInfoItem extends InfoItem`作为保存笔记信息的类

**Comment by 9rz9rz** [comment]
重构后大致结构如下：
```java
public abstract class InfoItem{

	public final long getId(){};
	public final String getDisplayString(){};//这是一般的getter
	

	private String displayString;
	private String content;
	private long id;

	// to be implemented
	abstract void show(Context context);
}

public class LinkInfoItem extends InfoItem(){
	show(Context context){
	// 访问网页
	}
    //其他的留下
}
```
