### ISSUE TITLE
所有Item相关类的完善

### ISSUE THREAD

**Issue by vegepuppy** [vegepuppy/Garnet#20]
按照目前的设计，所有的Recyclerview所填充的内容，包括Group类和Item类（指TodoGroup类似的class和TodoItem类似的class）。在Recyclerview中，这些类往往会被点击，而在当前的设计中，他们的点击监听器由ViewHolder来设置，这是不合理的。
因此，这些类应该有一个成员变量Listener，用于存储自身的监听器。并设置相应的函数，在ViewHolder中使用这个函数进行初始化。

在分支new-branch-InfoItem中，我设计了两个类InfoItem, LinkItem。后者继承于前者，两者的主要区别主要在type不同，且自主设置的监听器不同。
这两者的设计非常初步，不完善，且继承关系不清楚，可以看看怎么完善，或者用于给重构提供新思路。

此外，每一个item是否应该包含一个context（所在的Fragment或Activity）

**Comment by 9rz9rz** [comment]
我觉得设计一个InfoItem类，然后扩展这个类的思路很好，也加强了app的可扩展性。我的意见分如下几个方面：

# 当前代码的问题

## 自身的成员变量listener问题

我觉得没有必要将其设计为成员变量，而是在构造函数中设置监听器就可以了。因为即使设置为成员变量，也只会在为对应的View设置监听器的时候会使用一次，其他时候不会用。IDE会提示'Field can be converted to local variable'

大致如下所示：

```java
public class InfoItem{
    public InfoItem(OnClickListener listener){
        this.view.setOnClickListener(listener)    
    }
}
```
由于没有IDE，可能方法名称有错误，但是大致是这样。

## `Type`变量的问题

我觉得这个变量应该没必要弄成字符串，做成一个内部的`public static final int SOME_TYPE`常数应该就行了，字符串比较多余。

另外，On second thought，我觉得甚至**不需要一个变量标识Info的类别**，我们可以将`InfoItem`设计为abstract类，从中extends（扩展的时候注意命名规范） LinkInfoItem, FileInfoItem（访问文件）, PicInfoItem（访问图片）……通过类的名称就可以代替你设计的`type`变量，可以通过Java的`instanceof`关键字访问。

# 建议的设计

试试修改一下目前设计的InfoItem类。将这个类设计为一个abstract类，然后设计其他的类来实现具体的XXXInfoItem。大致的思路如下：

- 并不需要设计相应的mListener私有变量，因为设置的Listener都是相同的OnClickListener，只是其中的OnClick方法覆盖的不同，没必要为每一个扩展了
- 扩展`InfoItem`这个抽象类时，必须实现一个接口`OnClick()`这接口就是扩展出来的`XXXInfoItem`被点击时做的事

# 几个问题

- 不是太懂为啥要提供一个没有`context`的构造函数和一个有`context`的构造函数
- 不是太懂`infoDisplay`的作用，没有找到这变量的usage
- 我觉得没必要每个变量都设计一个`public`的getter和setter吧，比如说id这些的肯定是不允许外面乱改的

**Comment by vegepuppy** [comment]
> 我觉得设计一个InfoItem类，然后扩展这个类的思路很好，也加强了app的可扩展性。我的意见分如下几个方面：
> 
> # 当前代码的问题
> ## 自身的成员变量listener问题
> 我觉得没有必要将其设计为成员变量，而是在构造函数中设置监听器就可以了。因为即使设置为成员变量，也只会在为对应的View设置监听器的时候会使用一次，其他时候不会用。IDE会提示'Field can be converted to local variable'
> 
> 大致如下所示：
> 
> ```java
> public class InfoItem{
>     public InfoItem(OnClickListener listener){
>         this.view.setOnClickListener(listener)    
>     }
> }
> ```
> 
> 由于没有IDE，可能方法名称有错误，但是大致是这样。
> 
> ## `Type`变量的问题
> 我觉得这个变量应该没必要弄成字符串，做成一个内部的`public static final int SOME_TYPE`常数应该就行了，字符串比较多余。
> 
> 另外，On second thought，我觉得甚至**不需要一个变量标识Info的类别**，我们可以将`InfoItem`设计为abstract类，从中extends（扩展的时候注意命名规范） LinkInfoItem, FileInfoItem（访问文件）, PicInfoItem（访问图片）……通过类的名称就可以代替你设计的`type`变量，可以通过Java的`instanceof`关键字访问。
> 
> # 建议的设计
> 试试修改一下目前设计的InfoItem类。将这个类设计为一个abstract类，然后设计其他的类来实现具体的XXXInfoItem。大致的思路如下：
> 
> * 并不需要设计相应的mListener私有变量，因为设置的Listener都是相同的OnClickListener，只是其中的OnClick方法覆盖的不同，没必要为每一个扩展了
> * 扩展`InfoItem`这个抽象类时，必须实现一个接口`OnClick()`这接口就是扩展出来的`XXXInfoItem`被点击时做的事
> 
> # 几个问题
> * 不是太懂为啥要提供一个没有`context`的构造函数和一个有`context`的构造函数
> * 不是太懂`infoDisplay`的作用，没有找到这变量的usage
> * `belong`为啥是`long`类型的`private long belong`
> * 我觉得没必要每个变量都设计一个`public`的getter和setter吧，比如说id这些的肯定是不允许外面乱改的
> * 还有我在想，现在有没有必要设计上层的抽象类，因为目前我们只设计了链接类型info的处理，其他类型的还没想好，不如先设计一个其他类别的InfoItem，比如一个TextInfoItem，然后我们看看TextInfoItem和LinkInfoItem有什么共同点，最后再设计上层的抽象类？因为目前来看只有一种InfoItem的话，设计一个父类再extend就比较多余了
