### ISSUE TITLE
主页问题

### ISSUE THREAD

**Issue by pkdhit** [vegepuppy/Garnet#24]
我现在的问题是文本显示的list会重复出现，而且文本内容不会竖着排，代码已经更新上去了，可以的话就写注释告诉我问题，谢谢你们
![B49AC386C2A42E6310D51476BDC13632](https://github.com/user-attachments/assets/6183dae0-ce3f-491c-aa2a-8ceb06f6fefe)

**Comment by 9rz9rz** [comment]
```java
task_view.append(item);
```
大概是这一行导致的显示列表问题。

**Comment by vegepuppy** [comment]
![image](https://github.com/user-attachments/assets/bc99b816-438c-4f9b-b439-d4dcd28d6d0a)
这个position似乎没用上
![image](https://github.com/user-attachments/assets/82148d8c-0cda-447f-8dee-4196c1e23583)
这里的append方法是把字符串添加到textView后面，我们之前也没用过
![image](https://github.com/user-attachments/assets/58c6da39-238e-409c-be87-a7edadea6c20)
这里的返回值应该是你的标题列表的size()，这个列表应是{"高等数学","线性代数","电路"}这种

可以先不用写内层的嵌套，把外层先完善

**Comment by 9rz9rz** [comment]
应该改好了吧，close了
