### ISSUE TITLE
数据库类的问题

### ISSUE THREAD

**Issue by 9rz9rz** [vegepuppy/Garnet#25]
目前数据库类的设计是：

```java
public static class DataBaseAction{

    public void init()

    public void closeDataBase() // currently unused

    // other data delete, update, insert methods
}
```

但是这样做有问题。

1. 不知道什么时候调用closeDataBase()方法。如果在一个Activity的OnDestroy方法内调用`closeDataBase()`，那么在任何另一个Activity中访问数据库之前都必须调用`init()`方法，实在没有必要。
2. 目前的设计是数据库全程不关闭，没有调用过`db.close()`方法，这样可能会影响性能
3. 暂时的想法是把`init()`改成私有方法，在每次读写前打开数据库，读写完毕后关闭数据库，这样可能性能更好？

由于我们的数据量实在太小，应用功能也少。暂时看不出优化与不优化的从性能上的区别在哪里。但是如果要求在每一个Activity中都重新`init()`，我认为极易引起不易排查的bug，为开发造成麻烦。

综上，建议抽空略微重构一下`DataBaseAction`类。

**Comment by vegepuppy** [comment]
在我今天的测试中，我遇到了与此相关的问题。我本来在InfoDisplayActivity中，补充了onDestroy方法，并在里面关闭了数据库，这导致了运行时报错
``` 
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.garnet/com.example.garnet.InfoItemDisplayActivity}: java.lang.IllegalStateException: attempt to re-open an already-closed object 
```
因此，数据库不能轻易关闭，只能在应用结束时关闭，因此关闭的时机应当重新设置，甚至mainActivity中也不要在onDestroy中关闭

**Comment by 9rz9rz** [comment]
尝试修正此问题时，发现在获得SQLiteOpenHelper的时候，必须获取应用的Context，这应当是我当时设计init()方法的原因。但是实践已经表明这样的设计极易引起问题。因此我尝试将DataBaseAction与原来的GarnetDataBaseHelper合并，由这个Helper来进行数据的读写。试试是否可行
