### ISSUE TITLE
目前发现的一些问题

### ISSUE THREAD

**Issue by vegepuppy** [vegepuppy/Garnet#28]
目前发现了一些细节上的问题，我还没有改动，以`TODO`的形式标注在代码中了
- DataBaseAction 
    - 15行，这里将title表的表名设置为了常量，其他的应该也需要
    - 69行，这里返回值和参数有问题，已经修改了
    - 83行，这里的变量`titleFound`储存的实际上是uri，取名似乎不妥
    - 179行，这里直接访问了InfoItem的成员变量，是不是没有设置private
- InfoFragment
    - 140行，这里之前用的是title，现在被改成了name，别处还存在混用，命名需要统一一下

还有一些设计上的问题，没有打`TODO`，这里列举一下
- InfoItem内只有一个uri，这样是无法实现显示内容和跳转连接分开的，目前还没有实现点击链接跳转浏览器，需要把类重构了再说
- 命名规范问题应当提上日程了

**Comment by 9rz9rz** [comment]
这个issue里面的东西好像都解决了吧，回头看看
