### ISSUE TITLE
获取连接标题初步实现——当前问题与后续工作

### ISSUE THREAD

**Issue by vegepuppy** [vegepuppy/Garnet#34]
初步实现了获取链接标题的功能，当前设计如下：
- 创建了工具类`LinkTitleFetch`，包含bilibili，知乎，csdn三个网页的专用title获取方法
- 在`LinkDisplayActivity`中，采用多线程进行网络访问，将获取到的标题设为对应TextView的文字属性

目前问题如下
- 知乎专用的获取方法存在问题，可以成功的从网页返回内容，但是返回的title是一个空字符，原因未知
- 无法向用户抛出错误信息，例如url不合法，访问网页失败。目前，采用的是将错误信息作为title返回，这个方法及其逆天，显然不对
- csdn部分需要额外处理获得的title，因为获取的title除了网页内显示的部分之外，还有一个以下划线开头的额外部分。由于某些标题本就含有下划线，所以不能简单的去除。（当然这个问题可以不解决，影响不大）
- 在`LinkDisplayActivity`中占用了点击监听器，应当把获取网页标题放在别出
- 之前尝试过Toast，所以在`LinkTitleFetch`中还传入了Activity，现在不需要了

为了完善功能，短期内应该做以下后续工作
- 重新设计InfoLinkActivity类，要有专门的时间来获取标题，同时要优化多线程逻辑
- 明确是否将标题存入数据库，以避免每次都要重复访问网页
- 明确异常抛出的方法，目前排除了toast
- 优化`LinkTitleFetch`，首先要删除所有的Activity传入

鉴于我们对这个操作都不熟悉，我先以Q＆A的形式否定一些设想

- Q：为什么不用Toast
- A：Toast只能在主线程（UI线程）发出，这里打开网页用了多线程

- Q：为什么要多线程
- A：因为访问网页不能在主线程上进行，否则会报错

- Q：为什么现在`LinkTitleFetch`中的三个方法内部一模一样，为什么不做成统一的
- A：因为每个网页的访问方式可能有不同，例如上文提到知乎返回的是空字符，肯定要单独。此外，每个网页需要提供的反爬信息不同

注意，由于这次实现及其不成熟，所以我先不合并到主分支上。由于导入了第三方库，你们pull之后如果要build会有新的下载，不必惊慌。

@9rz9rz 
BTW，你推荐的Commit辅助插件确实好用，但是会生成GitCommitMessageStorage.xml文件，这会产生不必要的merge冲突，有什么好的解决办法吗

**Comment by 9rz9rz** [comment]
@vegepuppy 我进行了一些修改，提交在fix-fetch-link这个分支里。你看看要是没问题就把我们两个的branch合并一下删除一个留下一个就行。

# 测试用例及效果

我用于测试的链接包括：

```
https://www.bilibili.com/video/BV146421Z7Dp/?spm_id_from=333.1007.tianma.2-1-4.click&vd_source=3659676762c0220a430bf1be7c50d787
https://www.baidu.com
https://blog.csdn.net/csdn_aiyang/article/details/88297120
https://www.cnblogs.com/coder-programming/articles/11955844.html
https://www.zhihu.com/question/620247371/answer/3206676894
https://www.zhihu.com/column/c_1408443247228694528
```

上述链接在我删除了"user-Agent"那一长串之后仍然可以正常显示。且CSDN上面也没有出现问题。截图如下：
![Snipaste_2024-07-22_00-11-45](https://github.com/user-attachments/assets/5566c606-fc90-41f0-85e5-9673b8e7c447)

不过知乎问答确实返回空字符串了。但知乎专栏正常显示。这应当是与之前知乎的某个反爬策略有关系。我们应该不能解决。根据我前几天学习到的一些浅陋的HTML知识，推测原理如下：获得链接的标题应该是通过uri得到HTML文件，从文件的`<title>example<\title>`这一行里面获得标题"example"。返回空字符串应该是因为知乎的<title>这个属性设置的就是空。大略是可以通过模拟浏览器访问来获得单个页面的标题的（正如我们用浏览器访问知乎的时候，标签页上也正确显示了标题）但是这与我们的项目相关度太差，暂不考虑花大量精力去解决这个小问题吧。

# 解决的问题

1. 关于Toast的问题，我改为根据线程传出的message，在setText()之前加一个判断。如果无法获取就打印获得的信息，将其显示在Toast中。 **我采取的是不太安全的方法，两边都用的字符串字面量，其实应该用常量的**
2. 删除了线程的Context变量
3. 由于里面的是函数而不是类，修改XXXTitleFetcher为fetchXXXTitle
4. 由于三个函数都一样的，为了便于调试，只保留了一个。且经过调试没发现有需要三个函数的必要（这样一来LinkTitleFetcher这个类就不必要了，但我没删）
5. 删除了"User-Agent"那一长串，发现Bilibili上的标题仍然可以正常爬取

# 建议

1. 封装的问题先不忙。因为我们这个期望的最终功能也不是这样。目前别写的太乱就行。
2. 我觉得没有必要这样调试。直接在onConfirm()方法里面处理字符串就行了。没必要注释掉那里，到时候还要改回来
3. 数据库里面肯定是需要加一列的。现在的LINK表示意如下：
```
+-----+-----------------------+--------+------------+--+--+--+--+--+--+
| _id | URI                   | BELONG | DISPLAY    |  |  |  |  |  |  |
+-----+-----------------------+--------+------------+--+--+--+--+--+--+
| 1   | https://www.baidu.com | 高数     | 百度一下，你就知道  |  |  |  |  |  |  |
| 2   | …                     | …      | …          |  |  |  |  |  |  |
| 3   | …                     | …      | …          |  |  |  |  |  |  |
|     |                       |        |            |  |  |  |  |  |  |
|     |                       |        |            |  |  |  |  |  |  |
|     |                       |        |            |  |  |  |  |  |  |
|     |                       |        |            |  |  |  |  |  |  |
|     |                       |        |            |  |  |  |  |  |  |
|     |                       |        |            |  |  |  |  |  |  |
+-----+-----------------------+--------+------------+--+--+--+--+--+--+
```
你们可能也会用到这工具：https://tableconvert.com/ 用文字形式展示表格。

4. 返回的消息我设想新建立一个类：`LinkTitleFetcherMessage`
```java

public class LinkTitleFetcherMessage(){
    String title; // 获得的标题
    boolean isAccessable; //是否成功访问
}

```

网址无效就直接在onConfirm那里处理一下，`fetchLinkTitle()`函数处理`java.lang.IllegalArgumentException`异常的时候就不用单独设计一个布尔变量了。而原来的：

```java
String response = (String)msg.obj;
```
改成
```java
LinkTitleFetcherMessage response = (LinkTitleFetcherMessage) msg.obj
```
并用相应的getter和setter处理一下即可。我在push过后尝试了一下，但是出了点小问题，今天太晚就不改了，也没发上来，不过这个思路应该是可行的。

**注意到**这里msg.obj实际上有点像python的风格，很奇怪，不知道为啥没有用getter和setter

5. 封装

# Wrap-up

其实经过你的这番操作，我们已经实现了从链接获取标题的问题。看来是不难的。下面我们要做的事情有：

- 数据库里面加上`DISPLAY`这一列
- 把注释掉的代码放回来，用户确定添加链接的时候就获取链接标题并存储到数据库中
- 点击InfoItem相关的CardView的时候，访问对应链接
