### ISSUE TITLE
`NoteActivity`保存数据的方式修正

### ISSUE THREAD

**Issue by 9rz9rz** [vegepuppy/Garnet#54]
在`NoteActivity`中，因为没有找到合适的更新数据方法。目前的程序逻辑是：

1. 用户在`NoteActivity`中写作笔记
2. 用户点击返回键时，调用`NoteActivity`的`onDestroy()`方法，将笔记保存到数据库中
3. 这时候，`InfoItemDisplayActivity`中的`InfoItem`并没有对应更新，还存留的是原来的数据，因此会丢失用户的修改

目前，采用的是简单粗暴的使用`finish()`方法，用户点击某个`InfoItem`之后直接结束`InfoItemDisplayActivity`，从而强制在第二次进入`InfoItemDisplayActivity`中再次读取数据库中的内容

**Comment by vegepuppy** [comment]
从生命周期入手，如果可以，关联待办那里也要改

**Comment by vegepuppy** [comment]
从生命周期入手发现，noteActivity关闭过程中的任何方法，都发生在DisplayActivity恢复过程之后，因此，不能在单纯的用返回键代替保存键，应当有单独的保存时机
