### ISSUE TITLE
Settings页面

### ISSUE THREAD

**Issue by 9rz9rz** [vegepuppy/Garnet#57]
界面美化和文字提示优化

- 删掉 FAB
- 改成每日早晨通知
- 布局要美化

**Comment by vegepuppy** [comment]
目前需要修改的两个地方
- 授权失败的特殊返回
- SharedReference相关字符串常量化
如果可以，对定时功能进行测试

**Comment by vegepuppy** [comment]
授权的问题很大：
- 通过Activity打开设置页面的方法，与UI线程是异步的，因此无论如何都无法根据权限的获取情况来设置SwitchCompat的打开情况
- 我看到一个requestPermission方法，但是无法实践，原因是无法识别Manifest.permission中的String常量

**Comment by vegepuppy** [comment]
还是用Activity Results API，这几处都能解决
